# Generated by Django 4.2.6 on 2023-10-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amonic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="contact",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="phone",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="title",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
