# Generated by Django 4.2.6 on 2023-10-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amonic", "0002_alter_office_contact_alter_office_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="contact",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
