# Generated by Django 4.2.6 on 2023-10-30 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("amonic", "0003_alter_office_contact_alter_office_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCrashReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата/время входа в систему"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=2048, verbose_name="Описание ошибки"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("software_crash", "Software Crash"),
                            ("system_crash", "System Crash"),
                        ],
                        max_length=32,
                        verbose_name="Причина ошибки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт пользователя об ошибке",
                "verbose_name_plural": "Отчёты пользователя об ошибках",
            },
        ),
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_date", models.DateTimeField(auto_now_add=True)),
                ("logout_date", models.DateTimeField(blank=True, null=True)),
                (
                    "crash_report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="amonic.usercrashreport",
                        verbose_name="Сообщение об ошибке",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал активности пользователя",
            },
        ),
    ]
