# Generated by Django 4.2.6 on 2023-11-03 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickets",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="tickets",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="tickets",
            old_name="passport_county",
            new_name="passport_country",
        ),
    ]
