# Generated by Django 4.2.6 on 2023-11-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_amenities_amenitiestickets_amenitiescabintype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickets",
            name="booking_reference",
            field=models.CharField(max_length=6),
        ),
    ]
